apiVersion: monitoring.licious.app/v1alpha1
kind: EndpointMonitor
metadata:
  name: redis-check
  namespace: endpoint-monitoring-operator-system
spec:
  driver: redis
  endpoint: redis.example.com:6379
  checkInterval: 30
  notify:
    slack:
      enabled: true
      webhookUrl: https://hooks.slack.com/services/XXXXXXXXX/YYYYYYYYY/ZZZZZZZZZZZZ
      alertOn:
        - failure