apiVersion: monitoring.licious.app/v1alpha1
kind: EndpointMonitor
metadata:
  name: smtp-check
  namespace: endpoint-monitoring-operator-system
spec:
  driver: smtp
  endpoint: smtp.example.com
  checkInterval: 30
  notify:
    slack:
      enabled: true
      webhookUrl: https://hooks.slack.com/services/XXXXXXXXX/YYYYYYYYY/ZZZZZZZZZZZZ
      alertOn:
        - failure