apiVersion: v1
kind: Secret
metadata:
  name: valkey-credentials
  namespace: endpoint-monitoring-operator-system
type: Opaque
stringData:
  # Optional. Omit username for password-only AUTH.
  username: default
  password: changeme
