apiVersion: monitoring.licious.app/v1alpha1
kind: EndpointMonitor
metadata:
  name: trino-basic-http-check
  namespace: endpoint-monitoring-operator-system
spec:
  checkInterval: 60  # check every 1 minute
  driver: http
  endpoint: https://status.example.com/
  notify:
    webhook:
      enabled: true
      webhookUrl: https://hooks.slack.com/services/XXXXXXXXX/YYYYYYYYY/ZZZZZZZZZZZZ
      contentType: "application/json"
      contents: |-
        {{- $icon := "ℹ️" -}}
        {{- if eq .Status "success" -}}{{- $icon = "✅" -}}{{- else if eq .Status "failure" -}}{{- $icon = "❌" -}}{{- end -}}
        {
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": {{printf "%q" (printf "%s %s %s changed status to %s" $icon .Driver .Endpoint .Status)}},
                "emoji": true
              }
            },
            {
              "type": "section",
              "text": {
                "type": "plain_text",
                "text": {{printf "%q" (printf "%s" .Message)}}
              }
            }
          ]
        }
      alertOn:
      - change
